name: Bug Report
description: Found something you weren't expecting? Report it here!
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        # NOTE
        - Please speak English, this is the language all maintainers can speak and write.
        - Make sure you are using the latest release and
        - take a moment to check that your issue hasn't been reported before.

  - type: input
    id: version
    attributes:
      label: Version
      description: |
        Version of SpoofDPI that you are currently using
        This can be shown by running "spoof-dpi -v" in terminal
    validations:
      required: true

  - type: input
    id: os-ver
    attributes:
      label: Operating System
      description: The operating system and version you are using
    validations:
      required: true

  - type: textarea
    id: run-info
    attributes:
      label: How are you running SpoofDPI?
      description: |
        Please include information on whether you built Gitea yourself, used one of our downloads, are using https://demo.gitea.com or are using some other package
        Please also tell us how you are running Gitea, e.g. if it is being run from docker, a command-line, systemd etc.
        If you are using a package or systemd tell us what distribution you are using
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a description of your issue here
    validations:
      required: true
